### ISSUE TITLE
Create big button for new document in Recent window

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#106]
Place it first in front of recent documents to make it big, not small one in toolbar

**Comment by prokhorovxo** [comment]
@akaDuality can I take this one?

**Comment by drucelweisse** [comment]
> @akaDuality can I take this one?

if you want, i can assign you as well

**Comment by akaDuality** [comment]
@prokhorovxo yes!

@drucelweisse you can do it next time

**Comment by prokhorovxo** [comment]
@drucelweisse @akaDuality 

guys I've a couple of options: `plus.circle` or `plus` icon with `white` or `systemGray` tint color. Which options do you like?

<img width="900" alt="Screenshot 2022-09-07 at 00 48 49" src="https://user-images.githubusercontent.com/29862757/188747054-b9eebaf6-b9d1-46b2-bb8d-3510cd6fe19d.png">

<img width="900" alt="Screenshot 2022-09-07 at 00 44 24" src="https://user-images.githubusercontent.com/29862757/188746587-75907b2b-ecab-4b62-b3e0-c3d87efb5de5.png">

**Comment by akaDuality** [comment]
Gray looks fine. Also you can add border around cell to show how big button's area. Probably, border can be dashed

**Comment by prokhorovxo** [comment]
<img width="949" alt="Screenshot 2022-09-07 at 21 53 44" src="https://user-images.githubusercontent.com/29862757/188955817-aa03fb14-9a68-4b03-b364-92ed2f9f90aa.png">
<img width="949" alt="Screenshot 2022-09-07 at 21 54 05" src="https://user-images.githubusercontent.com/29862757/188955822-994f4069-643a-4412-a0ac-57e557ec89d3.png">

I think dashed line looks much better, what do you think?

**Comment by akaDuality** [comment]
@prokhorovxo yeah, dashed is cooler!

**Comment by prokhorovxo** [comment]
@akaDuality ok, so I've prepared PR, but I can't set you as a reviewer
