### ISSUE TITLE
Update Repository Description

### ISSUE THREAD

**Issue by shawnjb** [VODGroup/VoiceOverDesigner#188]
I think the current repository description could be improved to better reflect the capabilities of the VoiceOver Designer app. Here is a suggestion for a new description:

> Design accessibility features for your iOS app with VoiceOver Designer, a macOS app that offers a range of design tools and generates specifications for developers. Preview your work on an iPhone with the companion app, VoiceOver Preview. Integrate with Figma for seamless workflow.

Please let me know what you think of this suggestion. Thank you!

**Comment by akaDuality** [comment]
Cool! But Figma's integration will be late this or the next year

**Comment by shawnjb** [comment]
Thank you for your response! I appreciate your input and understand that the Figma integration may not be available at this time. In light of this information, I suggest removing the mention of Figma integration from the initial suggestion. We can always revisit the idea of integrating with Figma at a later date if it becomes a possibility. Thank you again for your feedback!

**Comment by akaDuality** [comment]
Have updated yet, thanks a lot!
