### ISSUE TITLE
Textfield trait

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#191]
UITextField and UITextView have some special hidden trait that expose them to accesiblitiy technologies. We should investigate how to repeat this behaviour.

Also, UISwitch have special toggle-button trait.

Hidden traits according to [my another repository](https://github.com/akaDuality/AccessibilityTraits), bit mask:
```
19: "pickeritem",
20: "radio button",
23: "status bar item",
25: "inactive",
26: "footer",
28: "tab",
32: "visited",
35: "tap and hold, then move up and down to select index",
38: "draggable",
39: "learning",
40: "pop-up button",
42: "maths",
45: "hide from focus",
50: "folder",
52: "menu item",
53: "double tap to toggle settings",
59: "video playback",
60: "icon",
```

**Comment by drucelweisse** [comment]
From [this](https://gist.github.com/AndreasVerhoeven/65925ebb1a648c55e7a5dc4730c06be8) gist:

```objc
static UIAccessibilityTraits UIAccessibilityTraitTextEntry = 0x0000000000040000;
static UIAccessibilityTraits UIAccessibilityTraitIsEditing = 0x0000000000200000;
```

Which means in Swift it will be: 

```swift
static let textFieldTextEntry = UIAccessibility(rawValue: 262144)
static let isEditingEntry = UIAccessibility(rawValue: 2097152)
```

Checked in sumulator example and it magically works!


https://user-images.githubusercontent.com/36012972/211389453-ac625db7-4736-4328-854a-e639846c7892.MP4

**Comment by akaDuality** [comment]
Cool! UISwitch should be 53 number
