### ISSUE TITLE
Preview: move delete button to bottom, add Done button to top

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#213]
I have accidentally removed an item by hitting delete button :D It looks like bottom it better place for this kind of action

**Comment by drucelweisse** [comment]
I'm not sure, should delete button be in bottom toolbar like a "trash" icon or be fullwidth?

**Comment by akaDuality** [comment]
Fullwidth at the bottom of scrolling looks fine. It's not an often case to delete element I suppose. Trash icon is welcome addition to the button
