### ISSUE TITLE
iCloud capability failure

### ISSUE THREAD

**Issue by drucelweisse** [VODGroup/VoiceOverDesigner#26]
It seems that use of iCloud capability doesn't available on personal teams. As I delete that capability to be able to build app, it just crashes at creating new document as it trying to access iCloud Container. Is it possible to disable iCloud for development?

<img width="311" alt="Screenshot 2022-06-30 at 23 48 34" src="https://user-images.githubusercontent.com/36012972/176775744-bd40b937-ef91-4236-8785-d8041a7032c7.png">

**Comment by akaDuality** [comment]
I've replaced iCloud container with documents folder. Try to build from `master`

**Comment by akaDuality** [comment]
Also, have moved the project to an organisation: https://github.com/VODGroup/VoiceOverDesigner
