### ISSUE TITLE
Designer: open long files correctly

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#32]
Should resize window according to file height.

1. Create new window 
2. Drag'n'drop long file
3. Result: the window is resized according to file size

- [x] Draw an image at actual size
- [x] Scale the scrollView to fit the image's height
- [x] Add controls to change scale. 
- [x] Zoom [by scroll-wheel](https://stackoverflow.com/questions/62032442/how-do-i-animate-zoom-in-and-out-in-a-nsscrollview-so-that-it-is-smooth). Probably, CMD+scroll is enough
- [x] Check long images
- [x] Shortcuts
- [x] Fix insets of safe area
- [x] Hide zoom controls when there is no background image
- [x] Update samples
- [ ] Test Preview

**Comment by drucelweisse** [comment]
Is this still an issue as we have scrollview in editor?

**Comment by drucelweisse** [comment]
I'll try on that

**Comment by akaDuality** [comment]
@drucelweisse I'm going to fix it today or tomorrow. Have you done something or I can start from the beginning?

**Comment by drucelweisse** [comment]
You can start from the beginning, didn't commit anything yet

**Comment by akaDuality** [comment]
@drucelweisse thank you, working on that
