### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by bbsody** [VODGroup/VoiceOverDesigner#35]
Hey!

I've created a new app icon. It has two different versions, w/ and w/o the text on the marker (to use in smaller sizes). Unfortunately, it wasn't created in the P3 colour space, but I might update it later.

![AppIcon_no_text@4x](https://user-images.githubusercontent.com/694273/180649888-cdb7cd34-35b1-409e-a5f8-88c681a22960.png)
![AppIcon@4x](https://user-images.githubusercontent.com/694273/180649889-a0e3d22b-c01e-4542-805c-00fc42dc102a.png)
.

**Comment by akaDuality** [comment]
Can you create iOS version of this icon for Preview app?

**Comment by bbsody** [comment]
Ah, I forgot about the Preview app. Here you go!
![AppIcon_iOS](https://user-images.githubusercontent.com/694273/180663454-272946f1-5382-46be-994e-e5b8a75a0bdb.png)
