### ISSUE TITLE
Sometimes rect's colours dosn't discard

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#51]
As a result I have this picture
<img width="502" alt="Screen Shot 2022-07-29 at 01 11 17" src="https://user-images.githubusercontent.com/3120680/181829681-4f7cf590-a88e-4aed-a4c2-238373624654.png">

**Comment by drucelweisse** [comment]
I'll try it

**Comment by akaDuality** [comment]
Also, when selected orange is changed to valid green orange border keeps be orange :D

**Comment by akaDuality** [comment]
I've understand the problem: default alpha is not equal to normal alpha after highlighting

**Comment by drucelweisse** [comment]
You can found it in pr
