### ISSUE TITLE
Add labels over rectangles

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#9]
At the current moment the app not shows text for element's rectangles. It's not very big problem because the app contains a lot of text under rectangles, but we should have ability to present labels how it VoiceControl does.

- [ ] Create popover that can be shown over a rectangle like VoiceControl
- [ ] Create modifier button or mode that toggles popovers' visibility

**Comment by drucelweisse** [comment]
I would like to try on this issue. I've tried to show multiple popovers, but macOS limited to show only one at time. It looks like it needed to show custom view near rectangle, to look like the voice control label. 

Should it show A11yDescription label or I missing something?

**Comment by akaDuality** [comment]
Custom view near drawn rectangle is fine. Not necessary to drawn exactly like voice control, firstly we need mechanism to show this descriptions, good UI can be the next step.

**Comment by drucelweisse** [comment]
Should it be closed as pull request is merged?

**Comment by akaDuality** [comment]
Yeah, thank you!
