### ISSUE TITLE
Add localisation to all texts. And plural forms

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#91]
`A11yDescription` has text on Russian. We should make base-translation on English and translate back to Russian

**Comment by drucelweisse** [comment]
I'd like to do that, are there any resources how A11y localized?

**Comment by akaDuality** [comment]
You can find everything at [AccessibilitySnapshot](https://github.com/cashapp/AccessibilitySnapshot/blob/master/Sources/AccessibilitySnapshot/Core/Swift/Assets/en.lproj/Localizable.strings). English, German, Russian.

**Comment by akaDuality** [comment]
I think we should just copy files and after that rework our code to fit localization
