### ISSUE TITLE
Custom description

### ISSUE THREAD

**Issue by akaDuality** [VODGroup/VoiceOverDesigner#98]
The last part of control's description is custom actions. We already have storyboard sample, but need logic for this. The description can be accessed by vertical swipe like custom action. A sample can be viewed at default Photos on iPhone.

Document:
- [ ] Add custom description to Document. It's array of key-value pairs
- [ ] Add migration from previous format of documents

Designer:
- [ ] Create `CustomDescriptionViewController`
- [ ] Embed `CustomDescriptionViewController` to `Settings`
- [ ] Allow to add and remove new pairs, save descriptions

Preview:
- [ ] Add support

<img width="580" alt="Screen Shot 2022-08-21 at 14 10 57" src="https://user-images.githubusercontent.com/3120680/185784082-31cb2ad9-f451-46c2-81fa-1f37763117ad.png">

**Comment by drucelweisse** [comment]
I'll do that
